using System.Collections.Generic;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Adex.Data.Model.Migrations
{
    /// <inheritdoc />
    public partial class EntityAttributesAsJsonb : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Attributes are regenerated by the next import.
            migrationBuilder.Sql("TRUNCATE TABLE \"EntityAttributes\"");

            migrationBuilder.DropPrimaryKey(
                name: "PK_EntityAttributes",
                table: "EntityAttributes");

            migrationBuilder.DropIndex(
                name: "IX_EntityAttributes_EntityId_Name",
                table: "EntityAttributes");

            migrationBuilder.DropColumn(
                name: "Id",
                table: "EntityAttributes");

            migrationBuilder.DropColumn(
                name: "Name",
                table: "EntityAttributes");

            migrationBuilder.DropColumn(
                name: "Value",
                table: "EntityAttributes");

            migrationBuilder.AddColumn<Dictionary<string, string>>(
                name: "Data",
                table: "EntityAttributes",
                type: "jsonb",
                nullable: false);

            migrationBuilder.AddPrimaryKey(
                name: "PK_EntityAttributes",
                table: "EntityAttributes",
                column: "EntityId");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("TRUNCATE TABLE \"EntityAttributes\"");

            migrationBuilder.DropPrimaryKey(
                name: "PK_EntityAttributes",
                table: "EntityAttributes");

            migrationBuilder.DropColumn(
                name: "Data",
                table: "EntityAttributes");

            migrationBuilder.AddColumn<int>(
                name: "Id",
                table: "EntityAttributes",
                type: "integer",
                nullable: false,
                defaultValue: 0)
                .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            migrationBuilder.AddColumn<string>(
                name: "Name",
                table: "EntityAttributes",
                type: "character varying(200)",
                maxLength: 200,
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<string>(
                name: "Value",
                table: "EntityAttributes",
                type: "text",
                nullable: true);

            migrationBuilder.AddPrimaryKey(
                name: "PK_EntityAttributes",
                table: "EntityAttributes",
                column: "Id");

            migrationBuilder.CreateIndex(
                name: "IX_EntityAttributes_EntityId_Name",
                table: "EntityAttributes",
                columns: new[] { "EntityId", "Name" },
                unique: true);
        }
    }
}
