// <auto-generated />
using System;
using Adex.Data.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Adex.Data.Model.Migrations
{
    [DbContext(typeof(AdexContext))]
    [Migration("20261007091810_AddEntityAttributesAndDeclarationType")]
    partial class AddEntityAttributesAndDeclarationType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Adex.Data.Model.Entity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.ToTable("Entities");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Adex.Data.Model.EntityAttribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EntityId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EntityId", "Name")
                        .IsUnique();

                    b.ToTable("EntityAttributes");
                });

            modelBuilder.Entity("Adex.Data.Model.Company", b =>
                {
                    b.HasBaseType("Adex.Data.Model.Entity");

                    b.Property<string>("Designation")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("Adex.Data.Model.Link", b =>
                {
                    b.HasBaseType("Adex.Data.Model.Entity");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("From_Id")
                        .HasColumnType("integer");

                    b.Property<string>("Kind")
                        .HasColumnType("text");

                    b.Property<int>("To_Id")
                        .HasColumnType("integer");

                    b.HasIndex("From_Id");

                    b.HasIndex("To_Id");

                    b.ToTable("Links");
                });

            modelBuilder.Entity("Adex.Data.Model.Person", b =>
                {
                    b.HasBaseType("Adex.Data.Model.Entity");

                    b.Property<string>("FirstName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("LastName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("Adex.Data.Model.FinancialLink", b =>
                {
                    b.HasBaseType("Adex.Data.Model.Link");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("DeclarationType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.ToTable("FinancialLinks");
                });

            modelBuilder.Entity("Adex.Data.Model.EntityAttribute", b =>
                {
                    b.HasOne("Adex.Data.Model.Entity", "Entity")
                        .WithMany("Attributes")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entity");
                });

            modelBuilder.Entity("Adex.Data.Model.Company", b =>
                {
                    b.HasOne("Adex.Data.Model.Entity", null)
                        .WithOne()
                        .HasForeignKey("Adex.Data.Model.Company", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Adex.Data.Model.Link", b =>
                {
                    b.HasOne("Adex.Data.Model.Entity", "From")
                        .WithMany()
                        .HasForeignKey("From_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Adex.Data.Model.Entity", null)
                        .WithOne()
                        .HasForeignKey("Adex.Data.Model.Link", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Adex.Data.Model.Entity", "To")
                        .WithMany()
                        .HasForeignKey("To_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("From");

                    b.Navigation("To");
                });

            modelBuilder.Entity("Adex.Data.Model.Person", b =>
                {
                    b.HasOne("Adex.Data.Model.Entity", null)
                        .WithOne()
                        .HasForeignKey("Adex.Data.Model.Person", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Adex.Data.Model.FinancialLink", b =>
                {
                    b.HasOne("Adex.Data.Model.Link", null)
                        .WithOne()
                        .HasForeignKey("Adex.Data.Model.FinancialLink", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Adex.Data.Model.Entity", b =>
                {
                    b.Navigation("Attributes");
                });
#pragma warning restore 612, 618
        }
    }
}
