// <auto-generated />
using System;
using Adex.Data.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Adex.Data.Model.Migrations
{
    [DbContext(typeof(AdexContext))]
    partial class AdexContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Adex.Data.Model.Entity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Entities");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Adex.Data.Model.EntityAttribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EntityId", "Name")
                        .IsUnique();

                    b.ToTable("EntityAttributes");
                });

            modelBuilder.Entity("Adex.Data.Model.EntityTotal", b =>
                {
                    b.Property<Guid>("EntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("IncomingAmount")
                        .HasColumnType("numeric");

                    b.Property<int>("LinkCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("OutgoingAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric");

                    b.HasKey("EntityId");

                    b.HasIndex("Total");

                    b.ToTable("EntityTotals");
                });

            modelBuilder.Entity("Adex.Data.Model.Company", b =>
                {
                    b.HasBaseType("Adex.Data.Model.Entity");

                    b.Property<string>("Designation")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasIndex("Designation");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Designation"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Designation"), new[] { "gin_trgm_ops" });

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("Adex.Data.Model.Link", b =>
                {
                    b.HasBaseType("Adex.Data.Model.Entity");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("From_Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Kind")
                        .HasColumnType("text");

                    b.Property<Guid>("To_Id")
                        .HasColumnType("uuid");

                    b.HasIndex("From_Id", "Date");

                    b.HasIndex("To_Id", "Date");

                    b.ToTable("Links");
                });

            modelBuilder.Entity("Adex.Data.Model.Person", b =>
                {
                    b.HasBaseType("Adex.Data.Model.Entity");

                    b.Property<string>("FirstName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("LastName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasIndex("FirstName");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("FirstName"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("FirstName"), new[] { "gin_trgm_ops" });

                    b.HasIndex("LastName");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("LastName"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("LastName"), new[] { "gin_trgm_ops" });

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("Adex.Data.Model.FinancialLink", b =>
                {
                    b.HasBaseType("Adex.Data.Model.Link");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("DeclarationType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.ToTable("FinancialLinks");
                });

            modelBuilder.Entity("Adex.Data.Model.EntityAttribute", b =>
                {
                    b.HasOne("Adex.Data.Model.Entity", "Entity")
                        .WithMany("Attributes")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entity");
                });

            modelBuilder.Entity("Adex.Data.Model.Company", b =>
                {
                    b.HasOne("Adex.Data.Model.Entity", null)
                        .WithOne()
                        .HasForeignKey("Adex.Data.Model.Company", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Adex.Data.Model.Link", b =>
                {
                    b.HasOne("Adex.Data.Model.Entity", "From")
                        .WithMany()
                        .HasForeignKey("From_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Adex.Data.Model.Entity", null)
                        .WithOne()
                        .HasForeignKey("Adex.Data.Model.Link", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Adex.Data.Model.Entity", "To")
                        .WithMany()
                        .HasForeignKey("To_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("From");

                    b.Navigation("To");
                });

            modelBuilder.Entity("Adex.Data.Model.Person", b =>
                {
                    b.HasOne("Adex.Data.Model.Entity", null)
                        .WithOne()
                        .HasForeignKey("Adex.Data.Model.Person", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Adex.Data.Model.FinancialLink", b =>
                {
                    b.HasOne("Adex.Data.Model.Link", null)
                        .WithOne()
                        .HasForeignKey("Adex.Data.Model.FinancialLink", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Adex.Data.Model.Entity", b =>
                {
                    b.Navigation("Attributes");
                });
#pragma warning restore 612, 618
        }
    }
}
