// <auto-generated />
using System;
using Adex.Data.MetaModel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Adex.Data.MetaModel.Migrations
{
    [DbContext(typeof(AdexMetaContext))]
    partial class AdexMetaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Adex.Data.MetaModel.Entity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.ToTable("Entities");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Adex.Data.MetaModel.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Alias")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Members");
                });

            modelBuilder.Entity("Adex.Data.MetaModel.Metadata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Entity_Id")
                        .HasColumnType("integer");

                    b.Property<int>("Member_Id")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("Entity_Id");

                    b.HasIndex("Member_Id");

                    b.HasIndex("Value");

                    b.ToTable("Metadatas");
                });

            modelBuilder.Entity("Adex.Data.MetaModel.Link", b =>
                {
                    b.HasBaseType("Adex.Data.MetaModel.Entity");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("From_Id")
                        .HasColumnType("integer");

                    b.Property<string>("Kind")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("To_Id")
                        .HasColumnType("integer");

                    b.HasIndex("From_Id");

                    b.HasIndex("Kind");

                    b.HasIndex("To_Id");

                    b.ToTable("Links");
                });

            modelBuilder.Entity("Adex.Data.MetaModel.Metadata", b =>
                {
                    b.HasOne("Adex.Data.MetaModel.Entity", "Entity")
                        .WithMany()
                        .HasForeignKey("Entity_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Adex.Data.MetaModel.Member", "Member")
                        .WithMany()
                        .HasForeignKey("Member_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entity");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Adex.Data.MetaModel.Link", b =>
                {
                    b.HasOne("Adex.Data.MetaModel.Entity", "From")
                        .WithMany()
                        .HasForeignKey("From_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Adex.Data.MetaModel.Entity", null)
                        .WithOne()
                        .HasForeignKey("Adex.Data.MetaModel.Link", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Adex.Data.MetaModel.Entity", "To")
                        .WithMany()
                        .HasForeignKey("To_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("From");

                    b.Navigation("To");
                });
#pragma warning restore 612, 618
        }
    }
}
