<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="CsvHelper" />
    <PackageReference Include="Dapper" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="Npgsql" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Adex.Common\Adex.Common.csproj" />
    <ProjectReference Include="..\Adex.Data.MetaModel\Adex.Data.MetaModel.csproj" />
    <ProjectReference Include="..\Adex.Data.Model\Adex.Data.Model.csproj" />
  </ItemGroup>
</Project>
